[package]
name = "rcl"
version = "0.1.0"
authors = ["Martin Dahl <martin.dahl@gmail.com>"]
edition = "2018"

[dependencies]
paste = "1.0.4"
widestring = "0.4.3"

[build-dependencies]
bindgen = "0.57.0"
itertools = "0.10.0"
common = { path = "../common", version = "0.1.0" }

[features]
lock = []