name: Rust

on:
  push:
    branches: [ github_actions ]
  pull_request:
    branches: [ github_actions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  testing_rolling:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
          profile: minimal
          toolchain: stable
          override: true
    - run: env
    - uses: ros-tooling/setup-ros@v0.1
      with:
        required-ros-distributions: rolling
    - run: source /opt/ros/rolling/setup.sh
    - run: cargo test --verbose
